sudo: required
services:
  - docker


before_install:
  - docker build -t ghanisayani/docker-react -f Dockerfile.dev .

script:
  - docker run ghanisayani/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-canada-1-112261284368"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
